### ISSUE TITLE
CheckedFunc, CheckedBiFunc, CheckedInput, CheckedOutput, CheckedProc, CheckedBiProc and CheckedBytes

### ISSUE THREAD

**Issue by Vatavuk** [yegor256/cactoos#736]
Let's create them similar to `CheckedScalar` in #735

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#736](https://github.com/yegor256/cactoos/issues/736) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Thanks for your contribution, @vatavuk[/z](https://www.0crat.com/u/vatavuk)! If you would be a member of [the project](https://www.0crat.com/p/C63314D6Z), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#736](https://github.com/yegor256/cactoos/issues/736) assigned to @nikialeksey[/z](https://www.0crat.com/u/nikialeksey), here is [why](https://www.0crat.com/footprint/C63314D6Z/711954103). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
The job [#736](https://github.com/yegor256/cactoos/issues/736) assigned to @nick318[/z](https://www.0crat.com/u/nick318), here is [why](https://www.0crat.com/footprint/C63314D6Z/750816558). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@nick318[/z](https://www.0crat.com/u/nick318) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by nick318** [comment]
@0crat refuse

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.pm.Claims[107] java.lang.IllegalStateException: Duplicate claims are not allowed, can't add this: <?xml version="1.0" encoding="UTF-8"?>
<claim id="801532662">
   <created>2018-03-21T15:22:49.673Z</created>
   <type>Cancel order</type>
   <token>github;yegor256/cactoos;736;374976296</token>
   <author>nick318</author>
   <params>
      <param name="job">gh:yegor256/cactoos#736</param>
      <param name="repo">yegor256/cactoos</param>
      <param name="issue">736</param>
      <param name="comment">374976296</param>
   </params>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/736#issuecomment-374976296))

@nick318 The user @nick318[/z](https://www.0crat.com/u/nick318) resigned from [#736](https://github.com/yegor256/cactoos/issues/736), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/736#issuecomment-374976296))

@nick318 Job `gh:yegor256/cactoos#736` is not assigned, can't get performer

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @nick318[/z](https://www.0crat.com/u/nick318)

**Comment by 0crat** [comment]
The job [#736](https://github.com/yegor256/cactoos/issues/736) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C63314D6Z/801535771); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by Vatavuk** [comment]
@proshin-roman I think that `Checked*` classes should use `CheckedScalar` in their implementation.
Maybe you should consider raising an impediment until `CheckedScalar` is merged.
Example:
```java
public final class CheckedFunc<X, Y, E extends Exception> implements Func<X, Y> {

    private final Func<X, Y> origin;

    private final Func<Exception, E> func;

    public CheckedFunc(final Func<X, Y> orig, final Func<Exception, E> fnc) {
        this.origin = orig;
        this.func = fnc;
    }

    @Override
    public Y apply(final X input) throws E {
        return new CheckedScalar<>(
            () -> this.origin.apply(input),
            this.func
        ).value();
    }
}
```

**Comment by proshin-roman** [comment]
@Vatavuk I agree, all these Checked* classes should be based on CheckedScalar as it done for Unchecked* classes. So I put this issue on waiting. Thanks for the hint!

**Comment by proshin-roman** [comment]
@0crat wait until #735 is merged

**Comment by 0crat** [comment]
> @0crat wait until #735 is merged ([here](https://github.com/yegor256/cactoos/issues/736#issuecomment-375954648))

@proshin-roman The impediment for [#736](https://github.com/yegor256/cactoos/issues/736) was registered successfully by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by Vatavuk** [comment]
@proshin-roman Will you submit PR for this issue? #735 was solved 20 days ago.

**Comment by proshin-roman** [comment]
@Vatavuk Yes, I'm back from vacation and gonna create a pull request for this ticket in one-two days.

**Comment by 0pdd** [comment]
@Vatavuk the puzzle [#799](https://github.com/yegor256/cactoos/issues/799) is still not solved.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#736](https://github.com/yegor256/cactoos/issues/736) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Comment by 0pdd** [comment]
@Vatavuk the only puzzle [#799](https://github.com/yegor256/cactoos/issues/799) is solved here.
